### ISSUE TITLE
Fails to compile with MySQL 8.0

### ISSUE THREAD

**Issue by totalAldo** [jabberd2/jabberd2#192]
When compiling Jabberd 2.7.0 on FreeBSD 12.0 + MySQL 8.0.13 with:

make.conf
`DEFAULT_VERSIONS+= mysql=8.0`

compilation of Jabberd 2.7.0 fails with:
```
--- storage_mysql_la-storage_mysql.lo ---
/bin/sh ../libtool --quiet  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I..  -I/usr/local/include/mysql -I/usr/local/include/mysql -I/usr/include -I/usr/local/include -DLIBICONV_PLUG -I../c2s -I.. -O2 -pipe  -DLIBICONV_PLUG -fstack-protector -fno-strict-aliasing  -funsigned-char -MT storage_mysql_la-storage_mysql.lo -MD -MP -MF .deps/storage_mysql_la-storage_mysql.Tpo -c -o storage_mysql_la-storage_mysql.lo `test -f 'storage_mysql.c' || echo './'`storage_mysql.c
storage_mysql.c:588:5: error: use of undeclared identifier 'my_bool'
    my_bool reconnect= 1;
    ^
storage_mysql.c:609:55: error: use of undeclared identifier 'reconnect'; did you mean 'connect'?
    mysql_options(conn, MYSQL_OPT_RECONNECT, (void *)&reconnect);
                                                      ^~~~~~~~~
                                                      connect
/usr/include/sys/socket.h:662:5: note: 'connect' declared here
int     connect(int, const struct sockaddr *, socklen_t);
        ^
2 errors generated.
*** [storage_mysql_la-storage_mysql.lo] Error code 1

make[3]: stopped in /wrkdirs/usr/ports/net-im/jabberd/work/jabberd-2.7.0/storage
```
